const todos = [
  {
    id: 1,
    task: "Complete math homework on quadratic equations and submit it by tomorrow morning before the deadline.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-12",
    category: "Education",
  },
  {
    id: 2,
    task: "Buy groceries, including fresh vegetables, fruits, milk, bread, and other essential items for the upcoming week.",
    completed: true,
    priority: "Medium",
    dueDate: "2025-01-10",
    category: "Household",
  },
  {
    id: 3,
    task: "Call the electrician to fix the broken kitchen light and check the wiring issue in the living room.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-13",
    category: "Maintenance",
  },
  {
    id: 4,
    task: "Clean the house thoroughly, including vacuuming, dusting, and organizing the closets in all rooms.",
    completed: true,
    priority: "Low",
    dueDate: "2025-01-09",
    category: "Household",
  },
  {
    id: 5,
    task: "Prepare for the upcoming team meeting by creating a detailed presentation and reviewing all project updates.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-14",
    category: "Work",
  },
  {
    id: 6,
    task: "Finish reading the book on personal finance to better understand investment strategies and wealth management.",
    completed: true,
    priority: "Medium",
    dueDate: "2025-01-11",
    category: "Personal Development",
  },
  {
    id: 7,
    task: "Reply to all pending emails, including responses to the project queries and scheduling a follow-up call.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-12",
    category: "Work",
  },
  {
    id: 8,
    task: "Organize the workspace by sorting files, labeling drawers, and decluttering unnecessary items on the desk.",
    completed: true,
    priority: "Low",
    dueDate: "2025-01-10",
    category: "Organization",
  },
  {
    id: 9,
    task: "Schedule a dentist appointment for a routine check-up and cleaning to ensure proper dental health.",
    completed: false,
    priority: "Medium",
    dueDate: "2025-01-15",
    category: "Health",
  },
  {
    id: 10,
    task: "Update the project documentation with the latest changes and ensure all team members have access to it.",
    completed: true,
    priority: "High",
    dueDate: "2025-01-13",
    category: "Work",
  },
  {
    id: 11,
    task: "Research the new framework for web development and create a summary of its features and benefits.",
    completed: false,
    priority: "Medium",
    dueDate: "2025-01-16",
    category: "Education",
  },
  {
    id: 12,
    task: "Water the indoor plants and make sure to remove any dried leaves or weeds from the pots.",
    completed: true,
    priority: "Low",
    dueDate: "2025-01-10",
    category: "Household",
  },
  {
    id: 13,
    task: "Plan a weekend getaway with family, including booking accommodations and creating an itinerary.",
    completed: false,
    priority: "Medium",
    dueDate: "2025-01-20",
    category: "Leisure",
  },
  {
    id: 14,
    task: "Update the resume with recent achievements and send it to the hiring manager for the new job opportunity.",
    completed: true,
    priority: "High",
    dueDate: "2025-01-18",
    category: "Career",
  },
  {
    id: 15,
    task: "Learn a new recipe and cook dinner for friends and family to celebrate the weekend together.",
    completed: false,
    priority: "Low",
    dueDate: "2025-01-14",
    category: "Leisure",
  },
  {
    id: 16,
    task: "Create a fitness routine and schedule workouts for the next month to achieve better health goals.",
    completed: true,
    priority: "Medium",
    dueDate: "2025-01-15",
    category: "Health",
  },
  {
    id: 17,
    task: "Backup all important files to an external hard drive and verify that the data is accessible.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-11",
    category: "Technology",
  },
  {
    id: 18,
    task: "Attend the webinar on cybersecurity to stay updated with the latest trends and tools in the industry.",
    completed: true,
    priority: "Medium",
    dueDate: "2025-01-12",
    category: "Education",
  },
  {
    id: 19,
    task: "Write a blog post on recent technological advancements and share it on social media platforms.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-17",
    category: "Personal Development",
  },
  {
    id: 20,
    task: "Fix the garden fence and plant new flowers to enhance the overall look of the backyard.",
    completed: true,
    priority: "Low",
    dueDate: "2025-01-13",
    category: "Household",
  },
  {
    id: 21,
    task: "Design a prototype for the upcoming project and present it to the team for feedback and improvements.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-19",
    category: "Work",
  },
  {
    id: 22,
    task: "Update the family photo album with recent pictures and memories from the past holiday season.",
    completed: true,
    priority: "Low",
    dueDate: "2025-01-16",
    category: "Leisure",
  },
  {
    id: 23,
    task: "Complete the online certification on data analysis and upload the certificate to LinkedIn.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-20",
    category: "Education",
  },
  {
    id: 24,
    task: "Organize the monthly budget and calculate expenses to ensure financial stability for the upcoming months.",
    completed: true,
    priority: "Medium",
    dueDate: "2025-01-14",
    category: "Finance",
  },
  {
    id: 25,
    task: "Build a new feature for the personal project and test it thoroughly for any bugs or errors.",
    completed: false,
    priority: "High",
    dueDate: "2025-01-22",
    category: "Technology",
  },
];

module.exports = todos;
